[project]
name = "synthetic-e-commerce-data-lake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=40.1.0",
    "google-cloud-pubsub>=2.34.0",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
]
